version: "3.3"

services:
  driver:
    build: .
    volumes:
      - type: bind
        source: .
        target: /driver
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
    - REDIS_HOST=redis
  redis:
    image: "redis:latest"
