version: "3.3"

services:
  driver:
    build: .
    volumes:
      - type: bind
        source: .
        target: /driver
    environment:
    - REDIS_HOST=redis
    command: yarn start
  redis:
    image: "redis:latest"
